# Project configuration
[project]
name = "demo-nuxt-app"
baseUrl = "http://localhost:3001"

[project.viewport]
width = 1280
height = 800

# Authentication settings (using environment variables)
[auth]
email = "${SCREENSHOT_LOGIN_EMAIL}"
password = "${SCREENSHOT_LOGIN_PASSWORD}"

# Recording settings
[recording]
output = "recordings/login-flow-with-pauses.mp4"
fps = 30
quality = 90

# Default typing configuration for all input steps
[recording.defaultTypeConfig]
slowType = false
typeDelay = 50  # Default to fast typing

# Demo recording steps
[[steps]]
type = "navigate"
path = "/login"

[[steps]]
type = "wait"
duration = 1000

[[steps]]
type = "startRecording"  # Explicitly start recording before login sequence

[[steps]]
type = "input"
selector = "[type='email']"
value = "${auth.email}"
typeConfig = { slowType = true, typeDelay = 150 }  # Override for slow typing

[[steps]]
type = "input"
selector = "[type='password']"
value = "${auth.password}"
# Uses default fast typing since no typeConfig specified

[[steps]]
type = "click"
selector = "[type='submit']"

[[steps]]
type = "wait"
duration = 1000

[[steps]]
type = "pauseRecording"  # Pause during the long loading time


# Navigate to content page
[[steps]]
type = "navigate"
path = "/content"

[[steps]]
type = "wait"
duration = 5000

[[steps]]
type = "resumeRecording" # Resume recording after the long loading time

# Select content type
[[steps]]
type = "select"
selector = "[data-test='content-type-select']"
option = "[data-test='content-type-twitter_post']"

[[steps]]
type = "wait"
duration = 500

# Select voice
[[steps]]
type = "select"
selector = "[data-test='voice-select']"
option = "[data-test='voice-Nativish']"

[[steps]]
type = "wait"
duration = 500

# Select action
[[steps]]
type = "click"
selector = "[data-test='action-select']"

[[steps]]
type = "wait"
duration = 1000

[[steps]]
type = "click"
selector = "[data-test='write_topic']"

[[steps]]
type = "wait"
duration = 1000

# Fill topic field
[[steps]]
type = "input"
selector = "[data-test='topic']"
value = "The Future of AI Development"
typeConfig = { slowType = true, typeDelay = 200 }

[[steps]]
type = "wait"
duration = 1000

# Fill additional instructions
[[steps]]
type = "input"
selector = "[data-test='additional_instructions']"
value = "Include specific examples of AI tools in development workflows."
# Uses default fast typing since no typeConfig specified

[[steps]]
type = "wait"
duration = 6000

[[steps]]
type = "stopRecording" 